#! /bin/bash

bat1=$(cat /sys/class/power_supply/BAT1/capacity)
bat0=$(cat /sys/class/power_supply/BAT0/capacity)
charge=$(cat /sys/class/power_supply/AC/online)

let "z = (( $bat1 + $bat0 )) / 2"

if [ $charge -eq 1 ]; then
  echo "    $z%"
else
  echo "   $z%"
fi
